package com.myproject.view;

import com.myproject.advinhapalavra.DefinirTentativas;
import com.myproject.advinhapalavra.SortearPalavra;
import com.myproject.util.ConferirChute;
import com.myproject.util.ValidacaoMaximoCaracter;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author biancamarques
 */
public final class Tela extends javax.swing.JFrame {

    int chutes = 1;
    int numeroTentativas;
    String palavraSecreta;
    String palavraOculta;
    public static ArrayList<String> listaAcertos = new ArrayList<>();
    ConferirChute conferirChute = new ConferirChute();
    String mensagem;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        TfChute.setDocument(new ValidacaoMaximoCaracter(1));
        palavraSecreta = SortearPalavra.executarSorteio();
        numeroTentativas = DefinirTentativas.definirNumeroTentativas(palavraSecreta);
        conferirChute.setPalavraSecreta(palavraSecreta);
        palavraOculta = "_ ".repeat(palavraSecreta.length());
        listaAcertoInicial();
        setarLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/fundo.jpg"));
        final Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            };
        };
        jLayeredPane1 = new javax.swing.JLayeredPane();
        LbPalavra = new javax.swing.JLabel();
        TfChute = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LbTentativa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Palavra"));

        LbPalavra.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N

        jLayeredPane1.setLayer(LbPalavra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TfChute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfChuteActionPerformed(evt);
            }
        });
        TfChute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfChuteKeyReleased(evt);
            }
        });

        jLabel2.setText("Chute:");

        LbTentativa.setFont(new java.awt.Font(".SF NS Text", 2, 10)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TfChute, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 277, Short.MAX_VALUE))
                    .addComponent(LbTentativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbTentativa, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TfChute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfChuteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfChuteKeyReleased
        String chute = TfChute.getText().toUpperCase();
        boolean acertou = conferirChute.conferir(chute);
        if (acertou) {
            inserirLetraNaPalavraOculta(chute);
        }
        setarLabels();
        limparTextField();
        if (chutes >= numeroTentativas && palavraOculta.matches(".*_.*")) {
            mensagem = "Você perdeu. A palavra secreta era " + palavraSecreta;
            fimJogo();
        }
        if (chutes < numeroTentativas && !palavraOculta.matches(".*_.*")) {
            mensagem = "PARABÉNS, VOCÊ VENCEU";
            fimJogo();
        }
        chutes = chutes + 1;


    }//GEN-LAST:event_TfChuteKeyReleased

    private void fimJogo() {
        int opcao = JOptionPane.showConfirmDialog(null, mensagem + "\nDeseja jogar novamente?", "FIM DE JOGO", JOptionPane.YES_NO_OPTION);
        if (opcao == 0) {
            Tela tela = new Tela();
            this.setVisible(false);
            tela.setVisible(true);
        } else {
            System.exit(0);
        }
    }

    private void limparTextField() {
        TfChute.setText("");
    }

    private void inserirLetraNaPalavraOculta(String chute) {
        char chuteChar = chute.charAt(0);
        for (int i = 0; i < palavraSecreta.length(); i++) {
            if (chuteChar == palavraSecreta.charAt(i)) {
                listaAcertos.set(i, chute);
            }
        }
        palavraOculta = "";

        for (int i = 0; i < palavraSecreta.length(); i++) {
            palavraOculta = palavraOculta + listaAcertos.get(i);
        }
    }

    public void listaAcertoInicial() {
        for (int i = 0; i < palavraOculta.length(); i++) {
            listaAcertos.add("_ ");
        }
    }

    private void setarLabels() {
        LbPalavra.setText(palavraOculta);
        LbTentativa.setText(chutes + " tentativas de " + numeroTentativas);
    }


    private void TfChuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfChuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfChuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbPalavra;
    private javax.swing.JLabel LbTentativa;
    private javax.swing.JTextField TfChute;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
